channels:
  - bioconda
  - conda-forge
  - r
  - rdonnelly
dependencies:
  # Python and general packages
  - python=3.7
  - jupyter=1.0.0
  - pandas
  - scipy
  - seaborn
  - matplotlib
  - nb_conda_kernels
  - numpy
  - scipy
    
  # Topology session
  - gseapy
  - leidenalg
  - python-igraph
  - pycairo
  - glpk
  - scikit-learn
  

